samples/MVCdiceGameEF/MVCdiceGame/Models/ChargeLog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdiceGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeLog
    {
        public int LogID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CreditCardNumber { get; set; }
        public decimal Amount { get; set; }
    }
}

samples/MVCdiceGameEF/MVCdiceGame/Models/LogEntityModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdiceGame.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogEntityModelContainer : DbContext
    {
        public LogEntityModelContainer()
            : base("name=LogEntityModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChargeLog> ChargeLogs { get; set; }
    }
}

samples/MVCdiceGameEF/MVCdiceGame/Models/LogEntityModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\kurt.friedrich\Desktop\AAA-Winter2017\ISIT-420winter17\5-ASP-MVCandEF\MVC\MVCdiceGame\MVCdiceGame\Models\LogEntityModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

samples/MVCdiceGameEF/MVCdiceGame/Models/LogEntityModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

samples/MVCdiceGameEF/MVCdiceGame/Controllers/RulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCdiceGame.Controllers
{
    public class RulesController : Controller
    {
        // GET: Rules
        public ActionResult Rules()
        {
            return View();
        }
    }
}

samples/MVCdiceGameEF/MVCdiceGame/Views/Home/Index.cshtml
@{
    ViewBag.Title = "The Game";
}



<h2>Welcome to the Dice Game, you need to pay before you play!</h2>
<h3>Please enter an amount to charge to your credit card.</h3>

@using (@Html.BeginForm("Play", "Home", FormMethod.Post))
{
    <p>
        First name:<br>
        <input type="text" name="TextFirstName" , value="Joe" style="width:150px" /> <br />
        Last name:<br>
        <input type="text" name="TextLastName" , value="Blow" style="width:150px" /> <br />
        Credit Card Number:<br>
        <input type="text" name="CreditCard" , value="12345678" style="width:150px" /> <br />
        Amount to Charge:<br >
        <input type = "text" name = "amount" , value = "10" style = "width:150px" /> <br />
        <input type="submit" value="Submit" />
    </p>
}

samples/MVCdiceGameEF/MVCdiceGame/Views/Home/Play.cshtml
@{
    ViewBag.Title = "Play";
}

<script language="JavaScript">
    function dice_roll(input) {
        var balance;
        if( document.form.balance.type == "hidden"){
            var y = document.getElementById("balance");
            y.type= "text";
            balance = input;
        }
        else {
            balance =  document.form.balance.value;
        }
        var valueInt = parseInt(balance);
        var roll = 0;
        var d1 = 0;
        var d2 = 0;
        d1 = Math.round(Math.random() * 6) % 6 + 1;
        d2 = Math.round(Math.random() * 6) % 6 + 1;
        roll = d1 + d2;
        if (balance != 0) {
            if (roll == 7 || roll == 11 || d1 == d2) {
                valueInt = valueInt + 1;
                document.form.textLose.value = "Won";
            }
            else {
                valueInt = valueInt - 1
                document.form.textLose.value = "Lost";
                if (valueInt == 0) {
                    document.form.textLose.value = "BUSTED";
                }
            }
            document.form.textD1.value = d1;
            document.form.textD2.value = d2;
            document.form.text.value = roll;
            document.form.balance.value = valueInt;
        }
        else {
            document.form.textD1.value = "";
            document.form.textD2.value = "";
            document.form.text.value = "";
        }
    }
</script>

<center>
    <h2>Let us help you get rid of your excess money.</h2>
    <h3>It is @DateTime.Now</h3>   <br />
    <h2>You started with $@ViewBag.chargeAmmount  </h2>

    <form name= "form">
        Your balance: $<input type="hidden" id="balance" size=5 name=balance value="0" >    <br /><br />
        <input type=button value="Roll Dice" name=button onclick="dice_roll( @ViewBag.chargeAmmount)">   <br /><br />
        Dice 1: <input type=text size=5 name=textD1> <br /><br />
        Dice 2: <input type=text size=5 name=textD2> <br /><br />
        Total: <input type=text size=5 name=text>   <br /><br />
        <input type=text size=5 name=textLose value="" >

</form>
</center>

samples/MVCdiceGameEF/MVCdiceGame/Views/Home/ShowLog.cshtml
@model IEnumerable< MVCdiceGame.Models.ChargeLog>
@{
    ViewBag.Title = "ShowLog";
}

<h2>ShowLog</h2>

<p>
    @Html.ActionLink("Index", "Home")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreditCardNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreditCardNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
           
        </tr>
    }

</table>

samples/MVCdiceGameEF/MVCdiceGame/Views/Rules/Rules.cshtml
@{
    ViewBag.Title = "The Rules";
}

<h2>Rules</h2>

You must first charge $10 to your credit card to play.
Everytime you bet you either loose a dollar <br />
or gain a dollar, based on winning or losing. <br />
You win when the total of your dice is 7 or 11. <br />
You loose for all other combinations. <br />

samples/MVCdiceGameEF/MVCdiceGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - An MVC App</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The Game", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>

            <div class="float-right">
                <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Pay First", "Index", "Home")</li>
                    <li>@Html.ActionLink("The Rules", "Rules", "Rules")</li>
                    <li>@Html.ActionLink("See Log", "ShowLog", "Home")</li>
                   
                </ul>
            </nav>
            </div>

        </div>
    </div>
    <h2>Yet Another Dice Game</h2>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            Copyright 2104 Kurt Friedrich
            <p>&copy; @DateTime.Now.Year - Dice Game Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>