420FinalEagleyKasner/420FinalEagleyKasner/Controllers/BrowserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _420FinalEagleyKasner.Models;
using _420FinalEagleyKasner.Models.ViewModels;

namespace _420FinalEagleyKasner.Controllers
{

    public class BrowserController : Controller
    {
        isit420FinalProjectEntities db = new isit420FinalProjectEntities();
        // GET: Browser
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FindCities(_420FinalEagleyKasner.Models.ViewModels.ViewModelCitySearch model)
        {
            float tempBorderWarm = 60;
            float tempBorderCold = 50;

            float TemperatureMin = model.TemperatureCold ? -999 : (model.TemperatureMild ? tempBorderCold : tempBorderWarm);
            float TemperatureMax = model.TemperatureWarm ? 999 : (model.TemperatureMild ? tempBorderWarm : tempBorderCold);


            var data = db.LivingCosts
                .Where(w => w.State1.Temperature.AverageTempF > TemperatureMin && w.State1.Temperature.AverageTempF < TemperatureMax).ToList();
            var viewData = data.Select(w=> new ViewModelCityResult(w));

            return View(viewData.ToList().OrderByDescending(w=>w.SalaryToCostOfLiving()).ToList());
        }

        public ActionResult AllSalaries()
        {
            return View(db.Salaries.OrderByDescending(w=>w.AnnualMeanWage).ToList());
        }
    }
}

420FinalEagleyKasner/420FinalEagleyKasner/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _420FinalEagleyKasner.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

420FinalEagleyKasner/420FinalEagleyKasner/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

420FinalEagleyKasner/420FinalEagleyKasner/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

420FinalEagleyKasner/420FinalEagleyKasner/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Best places in the USA to live as a programmer</h1>
    <p class="lead">
        We broke down and analyzed several cities across the US to find out 
        where we can have the cheapest lives and the best pay!
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h3>Browse with parameters</h3>
        <p>
            @Html.ActionLink("Browse Cities", "", "Browser")
        </p>
    </div>
    <div class="col-md-4">
        <h3>See the whole database</h3>
        <p>
            @Html.ActionLink("View All Salaries by State", "AllSalaries", "Browser")
        </p>
    </div>
    <div class="col-md-4">
        <h3>Coming soon!</h3>
        <p>
            @Html.ActionLink("Advanced mode", "Advanced", "Browser")
        </p>
    </div>
</div>